# Generated by Django 2.1.7 on 2019-02-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190225_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date', '-modified']},
        ),
    ]
