# Generated by Django 2.1.7 on 2019-02-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190225_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateField(null=True),
        ),
    ]
