# Generated by Django 2.1.7 on 2019-02-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190225_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date', '-modified']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='publish',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
