# Generated by Django 2.1.7 on 2019-02-26 16:42

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190226_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=article.models.upload_location),
        ),
    ]
