# Generated by Django 2.1.7 on 2019-02-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190226_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='article',
            name='width_field',
        ),
    ]
